### ISSUE TITLE
the trait `core::marker::Reflect` is not implemented for the type `T` [E0277]

### ISSUE THREAD

**Issue by paulosuzart** [iron/body-parser#51]
/home/suzart/.cargo/registry/src/github.com-1ecc6299db9ec823/bodyparser-0.0.5/src/lib.rs:116:1: 118:2 error: the trait `core::marker::Reflect` is not implemented for the type `T` [E0277]

Just found while compiling.

**Comment by paulosuzart** [comment]
I cloned and even adding Reflect to T, much more errors show up. Mostly around `the trait `core::clone::Clone` is not implemented for the type `errors::BodyError``. Unfortunately out of my abilities to fix this.

**Comment by reklis** [comment]
this is effectively the same issue as https://github.com/iron/body-parser/issues/54

**Comment by reem** [comment]
Fixed in master.
