### ISSUE TITLE
Switching from rustc-serialize to Serde

### ISSUE THREAD

**Issue by jimmycuadra** [iron/body-parser#63]
Would the maintainers be open to using Serde for deserializing JSON instead of rustc-serialize? If so, I'd be happy to submit a PR. Background: https://www.reddit.com/r/rust/comments/3we7fr/how_do_you_deal_with_upstream_crates_introducing/

**Comment by jimmycuadra** [comment]
It could also be provided as an option so that either rustc-serialize or serde would work, similar to how the toml crate works.

**Comment by reem** [comment]
Yes, we would be happy to integrate serde here. You may also be interested in the `params` crate (github.com/iron/params). Either a straight replacement of rustc_serialize with serde or a cargo feature for each would be good with me.

**Comment by jimmycuadra** [comment]
Fixed by #64.
